[package]
name = "opengl-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
egui = "0.30.0"
egui_glow = { version = "0.30.0", features = ["winit"] }
gl = "0.14.0"
glam = "0.29.2"
glutin = "0.32.1"
glutin-winit = "0.5.0"
hecs = "0.10.5"
image = "0.25.5"
winit = "0.30.7"
